api:
  baseUrl: http://0.0.0.0:3000
  version: api/v1

admin:
  url: http://0.0.0.0:9000
  recoverPath: /#/password-reset

mongodb:
  url: false

settings:
  registrationEnabled: true
  multiDomain: true

smtp:
  host: false
  port: false

storage:
  path: './storage'

system:
  initdb: false
