notifications:
  email: false
language: node_js
node_js:
- '8'
script:
- npm run build
cache:
  yarn: true
  directories:
  - apps/admin/node_modules
  - apps/api/node_modules
  - node_modules

deploy:
  - provider: script
    skip_cleanup: true
    script: ./bin/deploy-to-now.sh
    on:
      all_branches: true
